name: text_form_field_flutter
description: A highly customizable Flutter text form field widget with various label behaviors, styling options, and validation features.
version: 0.0.1
homepage: https://github.com/MansoorImtiaz/text_form_field_flutter
repository: https://github.com/MansoorImtiaz/text_form_field_flutter
documentation: https://github.com/MansoorImtiaz/text_form_field_flutter/blob/main/README.md
issue_tracker: https://github.com/MansoorImtiaz/text_form_field_flutter/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:


platforms:
  android:
  ios:
  web:
  macos:
  linux:
  windows:

topics:
  - form
  - widget
  - customizable
  - text-field